# config/packages/bing_ads_api.yaml
parameters:
  bing_ads_api:
    developer_token: '%env(BING_ADS_DEVELOPER_TOKEN)%'
    client_id: '%env(BING_ADS_CLIENT_ID)%'
    client_secret: '%env(BING_ADS_CLIENT_SECRET)%'
    audience_id: '%env(int:BING_ADS_AUDIENCE_ID)%'
    api_environment: 'production'
    oauth_scope: 'msads_manage'
    upload_directory: '%kernel.cache_dir%/bingads/uploads'
    oauth_refresh_token_path: '%kernel.cache_dir%/bingads/refresh_tokens.txt'
