services:
  _defaults:
    autowire: true
    autoconfigure: true

  Microsoft\BingAds\Auth\AuthorizationData:

  Microsoft\BingAds\Auth\ServiceClient:
    autowire: true
    arguments:
      $serviceClientType: 'CustomerManagementVersion13'
      $authorizationData: '@Microsoft\BingAds\Auth\AuthorizationData'
      $apiEnvironment: 'Production'

  App\Service\Authentication\Auth:
    autowire: true
    arguments:
      $config:
          developer_token: '%developer_token%'
          client_id: '%client_id%'
          client_secret: '%client_secret%'
          audience_id: '%audience_id%'
          api_environment: '%api_environment%'
          oauth_scope: '%oauth_scope%'
          upload_directory: '%upload_directory%'
          oauth_refresh_token_path: '%oauth_refresh_token_path%'
      $authorizationData: '@Microsoft\BingAds\Auth\AuthorizationData'
      $customerManagement: '@Coddict\BingAdsApiBundle\CustomerManagement'
      $customerManagementProxy: '@Microsoft\BingAds\Auth\ServiceClient'
      $bulkProxy: '@Microsoft\BingAds\Auth\ServiceClient'

  Coddict\BingAdsApiBundle\Service\Bulk\BulkHelper:
    autowire: true

  Coddict\BingAdsApiBundle\Service\Customer\CustomerListHelper:
    autowire: true
    arguments:
      $uploadDirectory: '%bing_ads_api.upload_directory%'
      $auth: '@Coddict\BingAdsApiBundle\Service\Authentication\Auth'
      $authorizationData: '@Microsoft\BingAds\Auth\AuthorizationData'
      $bulkHelper: '@Coddict\BingAdsApiBundle\Service\Bulk\BulkHelper'


