services:
  _defaults:
    autowire: true
    autoconfigure: true

  Coddict\BingAdsApiBundle\Service\Factory\ServiceClientFactory:
    autowire: true
    arguments:
      $config:
        developer_token: '%bing_ads_api.developer_token%'
        client_id: '%bing_ads_api.client_id%'
        client_secret: '%bing_ads_api.client_secret%'
        audience_id: '%bing_ads_api.audience_id%'
        api_environment: '%bing_ads_api.api_environment%'
        oauth_scope: '%bing_ads_api.oauth_scope%'
        upload_directory: '%bing_ads_api.upload_directory%'
        oauth_refresh_token_path: '%bing_ads_api.oauth_refresh_token_path%'
      $uploadDirectory: '%bing_ads_api.upload_directory%'

  Microsoft\BingAds\Auth\ServiceClient:
    factory: [ '@Coddict\BingAdsApiBundle\Service\Factory\ServiceClientFactory', 'createServiceClient' ]

  Coddict\BingAdsApiBundle\Service\Customer\CustomerListHelper:
    factory: [ '@Coddict\BingAdsApiBundle\Service\Factory\ServiceClientFactory', 'createCustomerListHelper' ]




