services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Service\Authentication\Auth:
    arguments:
      $config: '%bing_ads_api%'

  services:
    App\Service\CustomerListHelper:
      arguments:
        $uploadDirectory: '%bing_ads_api.upload_directory%'


