services:
  _defaults:
    autowire: true
    autoconfigure: true

  Coddict\BingAdsApiBundle\Service\Authentication\Auth:
    arguments:
      $config: '%bing_ads_api%'

  Coddict\BingAdsApiBundle\Service\Customer\CustomerListHelper:
    arguments:
      $uploadDirectory: '%bing_ads_api.upload_directory%'


